name: CI

on:
  push:
  pull_request:
    branches: [main]

jobs:
  test:
    strategy:
      matrix:
        scheme: [macOS, visionOS]
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Disable macro validation
        run: |
          defaults write com.apple.dt.Xcode IDESkipPackagePluginFingerprintValidatation -bool YES
          defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES

      - name: System Info
        run: |
          uname -a
          xcodebuild -version
          xcrun simctl list

      - name: Build
        run: xcodebuild -project Ensemble.xcodeproj -scheme ${{ matrix.scheme }} CODE_SIGNING_ALLOWED=NO
